
eureka:
  client:
    service-url:
      defaultZone: http://172.16.7.216:9001/eureka/,http://172.29.6.56:9001/eureka/
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    cache:
       enabled: false
  redis:
    host: 172.29.6.56
    port: 6379
zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 60000
  routes:
    order:
      path: /api/order/**
      service-id: order-server
    product:
      path: /api/procut/**
      service-id: product-server
    verification:
      path: /api/verification/**
      service-id: verification-server

