
eureka:
  client:
    service-url:
      defaultZone: http://172.16.7.216:9001/eureka/,http://172.29.6.56:9001/eureka/
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    cache:
       enabled: false
  redis:
    host: 172.29.6.56
    port: 6379
zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 60000
  routes:
    api-a:
      path: /order/**
      service-id: order-server
    api-b:
      path: /product/**
      service-id: product-server
    api-c:
      path: /verification/**
      service-id: verification-server

