
eureka:
  client:
    service-url:
      defaultZone: http://172.29.6.56:9001/eureka/
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    cache:
       enabled: false
zuul:
  routes:
    api-a:
      path: /order/**
    api-b:
      path: /product/**
