eureka:
  client:
    service-url:
      defaultZone: http://172.16.7.216:9001/eureka/,http://172.29.6.56:9001/eureka/
spring:
  transaction:
      rollback-on-commit-failure: 
  datasource:
      url: jdbc:mysql://172.29.6.56:3306/springcloud?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    cache:
       enabled: false
ribbon:
  eureka:
    enable: false
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
