eureka:
  client:
    service-url:
      defaultZone: http://172.16.7.216:9001/eureka/,http://172.29.6.56:9001/eureka/
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    cache:
       enabled: false
ribbon:
  eureka:
    enable: false
