eureka:
  client:
    service-url:
      defaultZone: http://172.16.7.216:9001/eureka/,http://172.29.5.62:9001/eureka/
spring:
  transaction:
      rollback-on-commit-failure: true
  datasource:
      url: jdbc:mysql://172.29.5.62:3306/springcloud?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    cache:
       enabled: false
ribbon:
  eureka:
    enable: false
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
