eureka:
  client:
    service-url:
      defaultZone: http://172.29.6.56:9001/eureka/
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    cache:
       enabled: false
reids:
    host: 172.29.6.56
    port: 6379
